version: '2.0'
services:
  db:
    image: influxdb:1.6-alpine
    env_file:
      - .env
    volumes:
      - influx:/var/lib/influxdb
  user-db:
    image: mongo:4-xenial
    volumes:
      - mongo:/data/db
  api:
    build: .
    depends_on:
      - db
      - user-db
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "8080:8080"
  nodered:
    build: nodered
    volumes:
      - nodered:/data
    env_file:
      - .env
    ports:
      - "1880:1880"
volumes:
  influx:
  mongo:
  nodered:
